# Generated by Django 5.2.5 on 2025-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, help_text='Unique student ID (e.g., STD001, STD002)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, help_text='Student number for enrollment (e.g., 2024001, 2024002)', max_length=20, null=True, unique=True),
        ),
    ]
